### ISSUE TITLE
Comparison with Cutie and XMem++

### ISSUE THREAD

**Issue by KaareLJensen** [Amshaker/MAVOS#1]
Your work looks very interesting and I am looking forward til you release the model so I will be able to try them out.

In your paper I can see that you compare your work with XMem as one of the better memory based VOS frameworks. But XMem have been preceeded by both [XMem++](https://github.com/max810/XMem2) and [Cutie](https://github.com/hkchengrex/Cutie) which both preforms better and/or faster than XMem.

Have you compare your work with those frameworks and if so, how do your work preform in relation to those two?

**Comment by Amshaker** [comment]
Hi @KaareLJensen ,

Thank you for your positive feedback!

XMem++ utilized a limited number of annotated frames, while our approach operates with just a single reference annotated frame as input. Consequently, comparing MAVOS directly with XMem++ may not yield a fair assessment due to the discrepancy in ground truth and supervision between both of them.

You make a valid point regarding the potential comparison with Cutie in terms of speed and performance. However, it's worth noting that at the time of our research, Cutie's paper hadn't been yet published. Exploring such a comparison in future studies could indeed offer valuable insights!

Best regards,
Abdelrahman.
